JC = javac

SRC_DIR = src/
CONST_SRC = usedConsts/
BIN_DIR = bin2/

#JFLAGS = -cp $(BIN_DIR)$(CONST_SRC)

Jenny:
	$(JC) -d $(BIN_DIR) $(JFLAGS) $(SRC_DIR)*.java $(SRC_DIR)$(CONST_SRC)*.java

#Constans:
#	$(JC) -d $(BIN_DIR) $(SRC_DIR)$(CONST_SRC)*.java